### ISSUE TITLE
update to androidx

### ISSUE THREAD

**Issue by satoshun** [satoshun/CoroutineBinding#33]

**Comment by satoshun** [comment]
done

**Comment by eygraber** [comment]
The [can-i-drop-jetifier plugin](https://github.com/plnice/can-i-drop-jetifier) says that com.github.satoshun.coroutinebinding:coroutinebinding:1.0.0-RC2 still depends on support libraries.

**Comment by eygraber** [comment]
To be more specific, it mentions a dependency on com.android.support:multidex:1.0.2 which may be only for testing so possibly ignore my comment :smile:
